### ISSUE TITLE
Viewer must filter out 'absent' and 'suppressed' issues by default

### ISSUE THREAD

**Issue by lgolding** [microsoft/sarif-visualstudio-extension#114]
For now, we should remove those issues entirely. In future, we can consider a UI affordance to display them.

**Comment by michaelcfanning** [comment]
We should make this issue a priority. For both of the 'absent' and 'suppressed' states, our behavior s/be to determine, at load time, whether the SARIF file contains either of these classes of issues. The SARIF spec states that all results must have these optional properties (either `result.baselineState` or `result.Suppressions`) or none of them will (so the viewer only has to examine a single result to determine whether these properties are in play). If the VS column relevant to the property (suppressions or whatever column governs the absent state) is *not* visible, it should be made visible and the column s/be configured to remove the suppressed or absent items from the view. We show the column as a UI clue that there are results which have been filtered away (increasing discoverability in cases where the user would like to check relevant filters to see absent/suppressed results).

In the case where this column is already visible, it should remain visible. We should investigate to see whether it's appropriate to retain previous column settings (if the user has enable viewing of suppressed/absent).

There is an established column for suppressed items in recent VS. Historically, the VS viewer has overloaded the 'Category' column for baseline state, but we might want to reconsider this.

For suppressed items, there is the additional wrinkle that many suppressions can be applied to a result, so we need to define a default behavior in this case. As a start, we could consider regarding a result as suppressed in cases where this is an active suppression, which is either in 'under review' or 'rejected' states (or if no state is given).

**Comment by mpande98** [comment]
- Don't want to overwhelm user with multiple suppressions
- Show column that allows you to view filtered items ` 
- For absent scenario, would we consider a slider paradigm in the SARIF viewer tab? 

More discussion required.

**Comment by lgolding** [comment]
@michaelcfanning wrote:

> As a start, we could consider regarding a result as suppressed in cases where this is an active suppression, which is either in 'under review' or 'rejected' states (or if no state is given).

Why would a "rejected" suppression cause us to regard the result as "suppressed"?

The [SARIF Tutorials](https://github.com/microsoft/sarif-tutorials) article [Displaying results in a viewer](https://github.com/microsoft/sarif-tutorials/blob/master/docs/Displaying-results-in-a-viewer.md) suggests:

> If the status of _any_ of the suppressions is `"underReview"` or `"rejected"`, then the result should _not_ be considered suppressed. Otherwise, the result _should_ be considered suppressed.
