### ISSUE TITLE
Embedded link with slash within anchor text does not work.

### ISSUE THREAD

**Issue by michaelcfanning** [microsoft/sarif-visualstudio-extension#117]
For example, try opening a test 

'[..\directory\myfile.cpp](https://example.com)]' is not correct.

This is due to the regex driving link discovery in `SdkUIUtilities.EmbeddedLinkPattern`. The <text> group will halt on encountering a backslash.  See the ^\\\\\\] segment below:

~~~
        // Embedded link format: [link text](n|uri) where n is a non-negative integer, or uri is an absolute URL
        private const string EmbeddedLinkPattern = @"\[(?<text>[^\\\]]+)\]\((?<target>[^)]+)\)";
~~~

@EasyRhinoMSFT may have some insight into why this exists or maybe there is a clue in the unit tess

**Comment by lgolding** [comment]
With this test file:

[Bug117.sarif.txt](https://github.com/microsoft/sarif-visualstudio-extension/files/4440873/Bug117.sarif.txt)

... the link now renders (and functions) properly:

![LinkWithBackslashes](https://user-images.githubusercontent.com/11762653/78606795-bd5db180-7812-11ea-9474-b3a7de846a75.png)
