### ISSUE TITLE
Integer links don't work

### ISSUE THREAD

**Issue by lgolding** [microsoft/sarif-visualstudio-extension#119]
Given the attached SARIF file, if you click on the link in the first issue (rule `TST0001`), it doesn't work. This is an integer link, and there is a `relatedLocation` with that `id`. If you click on the link in the second issue (rule `TST0002`), it works (assuming you have a real file at the location specified in the `file:` URI link).

[Bug119.sarif.txt](https://github.com/microsoft/sarif-visualstudio-extension/files/4441309/Bug119.sarif.txt)

**Comment by lgolding** [comment]
Integer links actually do work, but only when the `relatedLocation` specified by the integer link target has a `region`. So this is very likely the same bug as #121. But I won't resolve it duplicate until I've confirmed that.

**Comment by michaelcfanning** [comment]
FYI, critical to our scenario is that the viewer examine integer ids associated with related locations.

**Comment by lgolding** [comment]
> FYI, critical to our scenario is that the viewer examine integer ids associated with related locations.

Yes, that is exactly what the attached files demonstrate. FYI I have a fix.

**Comment by lgolding** [comment]
... and yes! The same fix takes care of #121, so I'm going to resolve that as duplicate.
