### ISSUE TITLE
Fixes don't recognize text-based regions

### ISSUE THREAD

**Issue by lgolding** [Microsoft/sarif-visualstudio-extension#12]
Repro:

1. Build and run the sarif-sdk sample application:
```
SarifSdkSample.exe create Test.sarif
```
2. Open `Test.sarif` in the viewer.
3. In the Error List Window, click on the issue `CA1820`.
4. In the SARIF Explorer Window, click **Fixes**.
5. Expand the tree nodes "Replace empty string with test for zero length", "Analysis Sample.cs"

Expected: It should display the "Deleted region" with proper row and column values.

Actual: It says "Start at offset 0".

**Comment by lgolding** [comment]
I don't know why I closed this.

**Comment by EasyRhinoMSFT** [comment]
The FixModel tests need to cover the conversion from SDK objects.
