### ISSUE TITLE
Prompt for file location omits last component of originalUriBaseId

### ISSUE THREAD

**Issue by lgolding** [microsoft/sarif-visualstudio-extension#127]
[Bug125.sarif.txt](https://github.com/microsoft/sarif-visualstudio-extension/files/4470943/Bug125.sarif.txt)

1. Save the attached file as .sarif.

2. Open it in VS.

3. Double-click on the single result.
    An Open File dialog opens.

Expected: The title of the dialog should be "Locate missing file c:\code\MyProject\src\io\kb.c"

Actual: The title of the dialog is "Locate missing file c:\code\MyProject\io\kb.c"

NOTE: This only happens if the `uri` property of the `originalUriBaseId` does _not_ end with a slash ('/'). In that case, the viewer's call to `new Uri(Uri uri, string relativePath)` interprets the final component of `uri` as a file name, strips it off, and combines the result with the relative URI. Whereas if the final slash is present, the final component of `uri` is interpreted as a directory name and correctly combined with the relative URI.

The SARIF spec (§3.14.14) `originalUriBaseId` does require the trailing slash, so a file like that attached is actually invalid. We should discuss whether the viewer should help out by appending the slash if it's missing.

@michaelcfanning FYI

**Comment by lgolding** [comment]
Agreed, the viewer should compensate for this even though it's not strictly valid SARIF without the trailing slash.

**Comment by michaelcfanning** [comment]
this problem is pervasive. everyone needs to code defensively against it, unfortunately. this should be a new validation rule for the SARIF validator.
