### ISSUE TITLE
Preview and Apply action links are disabled in Fixes

### ISSUE THREAD

**Issue by lgolding** [Microsoft/sarif-visualstudio-extension#13]
Repro:

1. Build and run the sarif-sdk sample application:
```
SarifSdkSample.exe create Test.sarif
```
2. Open `Test.sarif` in the viewer.
3. In the Error List Window, click on the issue `CA1820`.
4. In the SARIF Explorer Window, click **Fixes**.
5. Expand the tree nodes "Replace empty string with test for zero length", "Analysis Sample.cs"

Expected: The **Preview** and **Apply** links are enabled and work properly.

Actual: The links are disabled.

**Comment by EasyRhinoMSFT** [comment]
Enabled state is fixed by #14, but functionality is broken. I'll file a new issue for that one.
