### ISSUE TITLE
Viewer does not respect reportingDescriptor.defaultConfiguration

### ISSUE THREAD

**Issue by lgolding** [microsoft/sarif-visualstudio-extension#137]
[DefaultRuleConfiguration.sarif.txt](https://github.com/microsoft/sarif-visualstudio-extension/files/4552873/DefaultRuleConfiguration.sarif.txt)

In the attached sample, there are two rules, one whose `defaultConfiguration` specifies that it is an error and the other a warning. The viewer render the results for both rules as warnings, and the SARIF Explorer’s Info tab displays “Level: Warning”.

**Comment by yongyan-gh** [comment]
Cannot repo this issue in latest version.

The result is shown as error level according to rule defaultConfiguration. This is expected.

![image](https://user-images.githubusercontent.com/76094515/109338782-91c52a80-781b-11eb-8ec6-4248c4f9a5d1.png)

![image](https://user-images.githubusercontent.com/76094515/109338928-c33df600-781b-11eb-9c82-ddc8ad098452.png)

**Comment by eddynaka** [comment]
Marking as closed.
