### ISSUE TITLE
"Call Trees" => "Code Flows"

### ISSUE THREAD

**Issue by lgolding** [microsoft/sarif-visualstudio-extension#138]
In the SARIF Explorer, the "Call Trees" tab should be labeled "Code Flows" (on the principle of "ubiquitous vocabulary") since that is the SARIF term.

**Comment by eddynaka** [comment]
Closing this, since we are going to develop this change: https://github.com/microsoft/sarif-visualstudio-extension/issues/157

So, we changed from: "Call Trees" -> "Code Flows" -> "Analysis Steps"
