### ISSUE TITLE
Highlight is sometimes off by one column

### ISSUE THREAD

**Issue by lgolding** [microsoft/sarif-visualstudio-extension#140]
Here's an example where a rule detects the use of a potentially insecure API on column 9:

![Region](https://user-images.githubusercontent.com/11762653/82837525-2a3e1100-9e7e-11ea-9b1d-b4fa37dd8b06.png)

The source code shows that the column is correct, but the highlight starts in column 10:

![IncorrectHighlight](https://user-images.githubusercontent.com/11762653/82837577-58235580-9e7e-11ea-884e-6213050192df.png)

The [web viewer](https://microsoft.github.io/sarif-web-component/) gets it right:

![WebViewer](https://user-images.githubusercontent.com/11762653/82837651-8c971180-9e7e-11ea-9c7e-b3ed0201dbe2.png)

**Comment by michaelcfanning** [comment]
Resolved by https://github.com/microsoft/sarif-visualstudio-extension/pull/120
