### ISSUE TITLE
Viewer can't open SARIF functional test file

### ISSUE THREAD

**Issue by lgolding** [microsoft/sarif-visualstudio-extension#141]
If you open the SARIF SDK functional test file https://github.com/microsoft/sarif-sdk/blob/master/src/Test.FunctionalTests.Sarif/TestData/Multitool/ValidateCommand/ExpectedOutputs/SARIF1017.InvalidIndex_Invalid.sarif in the VS Extension, it throws the error "Value cannot be null. Parameter name: key".

**Comment by eddynaka** [comment]
I looked at this issue and i have the following findings:

- I had to update Sarif.* to the latest 2.2.5
- I had to comment everything related to SupressionState, this is one class that doesn't exist in Sarif.Sdk anymore

Let me know what do you think so I can create a PR.

**Comment by lgolding** [comment]
@eddynaka The `SuppressionState` enumeration was renamed to `SuppressionStatus`, and the `State` property of the `Suppression` object was renamed to `Status`. That was actually the very last change during the standardization process.

**Comment by eddynaka** [comment]
i see...are they the same thing? if yes, i can just rename and create a PR.

**Comment by lgolding** [comment]
Yes, that is just a rename. They mean exactly the same thing.

**Comment by lgolding** [comment]
It turns out that this bug is already fixed on the `master` branch, some time after the release of 2.1.8.

@eddynaka FYI.
