### ISSUE TITLE
Rename "CodeFlow" functionality to a less confusing term

### ISSUE THREAD

**Issue by HenokAddis** [microsoft/sarif-visualstudio-extension#157]
CodeFlow means git branch integrations in Windows, which may confuse people who see this feature.

Some ideas:
- Control Flow
- Analysis Steps
- Thread Flow

**Comment by michaelcfanning** [comment]
I like 'Analysis Steps' it seems very clear. @lgolding any thoughts?

**Comment by lgolding** [comment]
That sounds fine to me, too.

**Comment by HenokAddis** [comment]
+1 me too!

--
Henok Addis

**Comment by HenokAddis** [comment]
Reminder to apply a similar change to VSCode: https://github.com/microsoft/sarif-vscode-extension/issues/316

**Comment by eddynaka** [comment]
@yongyan-gh, check this and rename it to "Analysis Steps"

**Comment by yongyan-gh** [comment]
In current VS extension, the CodeFlow is displayed under "Call Trees" tab.
![image](https://user-images.githubusercontent.com/76094515/107134471-3c929a80-68a7-11eb-9b3f-2a3b1b9de892.png)

which is "Analysis Steps" in VS code.
![image](https://user-images.githubusercontent.com/76094515/107134496-6f3c9300-68a7-11eb-9164-e9267a24a955.png)

should we change vs extension tab "Call Trees" to "Analysis Steps" to be consistent with VS code?

**Comment by eddynaka** [comment]
@jeffersonking , do you remember about this issue? the VS-Extension is using "call Trees" based on what @yongyan-gh saw.
Should we change to "analysis steps" just like VSCode?

**Comment by jeffersonking** [comment]
Yes, "Analysis Steps" ended up being the agreed-upon name.
