### ISSUE TITLE
Viewer shows expansion chrome but expanding provides no additional information

### ISSUE THREAD

**Issue by michaelcfanning** [Microsoft/sarif-visualstudio-extension#16]
![image](https://user-images.githubusercontent.com/13526455/44407525-36f83d00-a513-11e8-930e-15ded5da09ef.png)

Load one of the new FxCop SARIF files to see this (checked in shortly)

**Comment by EasyRhinoMSFT** [comment]
Needs SDK package with Microsoft/sarif-sdk#pull/1048 and Microsoft/sarif-sdk/pull#1050
