### ISSUE TITLE
Visual Studio claims that SARIF Viewer is a cause of hangs in Visual Studio

### ISSUE THREAD

**Issue by HenokAddis** [microsoft/sarif-visualstudio-extension#160]
After running multiple VS Static Analysis builds, VS has claimed the SARIF Viewer is causing hangs in Visual Studio

![image](https://user-images.githubusercontent.com/46505299/89579465-acd13e00-d7e8-11ea-9542-0172c0ff45be.png)

![image](https://user-images.githubusercontent.com/46505299/89579805-413ba080-d7e9-11ea-8f54-0d7aa2dd9605.png)

**Comment by HenokAddis** [comment]
Our first suspricion is that this is possibly due to not responding quickly enough during a timeout window, causing VS to think that we are hung.

**Comment by Miaku** [comment]
@GabeDeBacker looked at this one - all of the SARIF parsing is happening on the UI thread. @lgolding and @jeffersonking will look into this.

**Comment by lgolding** [comment]
There are three contributors to the slowness:
- The model building happens on the UI thread.
- We eagerly build the code flow models for all results, when you only need it for the result you're looking at.
- The fact that we build the source map and most people don't need it.

**Comment by Miaku** [comment]
ETA: Full Fix ready by Thursday - could manifest as multiple PRs.
