### ISSUE TITLE
SARIF Viewer needs a Canary Private Gallery Link for validation with BETA users

### ISSUE THREAD

**Issue by HenokAddis** [microsoft/sarif-visualstudio-extension#162]
Today, we have Insiders and Production versions of the SARIF Viewers in both Visual Studio and VSCode. Unfortunately, given that we have much of our new infrastructure/features in the Insiders ring, everyone in Windows will also be living on that ring. Since every PR that is merged with master will get pushed to Insiders, everyone is on Canary.

With customers new to the experience and previous potential breaking changes making it to Production, we want to be more careful what features we want to release out to customers.

### [Our Choice] Create a New Release Pipeline Ring
In our build/release pipeline, we could add an additional ring structure layer before Insiders and Production called “Canary.” This would allow us to get some users on the freshest bits to stress-test some scenarios without breaking the world on any PR. This will also allow us to batch-release features/bug-fixes and share release notes with customers.

### Send out test bits prior to publishing
Before we push to Insiders, we validate that people have gone through a test matrix (Generation of test matrix is TBD; driven by Brian Collinwood from an email).

### Create a Maximum Allowed Version Check via WAVE
This idea will enable us to add a feature flag in WAVE that puts people either in a "Canary" or "Insiders" state. Based on their state, there is a max approved version: Canary = update at PR time; Insiders = Do not update beyond max version <foo>.

In VisualStudio, **I personally believe we should just make a private gallery similar to https://aka.ms/wavevs2019canary** and use this for our internal users who will take breaking changes. We should also rollout to users who we want on more stable rings via the public marketplace extension.

- **This is of course only if we're able to commit to pushing to PROD every 2-3 weeks minimum**

**Comment by Miaku** [comment]
Action item: @HenokAddis to work with @GabeDeBacker and Larry to see what build pipelines we need to set up for this.

**Comment by HenokAddis** [comment]
After our MWF triage we decided to go with a two-ring model for both VS and VSCode extensions.
-	In VSCode, we will use SARIF Prod as a stable ring that gets tested releases every 2-4 weeks; SARIF Insiders as the BETA ring
-	In VS, we will use the Public Marketplace SARIF as a stable ring that gets tested releases every 2-4 weeks; SARIF Insiders is a ring we need to create through the private gallery model

I want to start this thread to begin setting up a private gallery for SARIF Visual Studio Insider releases. In Michael’s absence, I’m looking to Larry for guidance and consultation! Gabriel let me know if you need more information than what is below too.

Why should we do this?
-	This will enable us to release more broadly to our users internally using the Public Marketplace as a stable version, and to BETA testers as an “Insiders” version.
-	This will allow better validation of our scenarios before we push this to the general audience that uses the Public Marketplace extension outside of Windows
-	This is a tried-and-true model that is used by many extensions, [see this link for the publicly available documentation from Visual Studio.](https://devblogs.microsoft.com/visualstudio/create-a-private-gallery-for-self-hosted-visual-studio-extensions/)

Current information
-	The VS Sarif Extension is built using this MSENG build pipeline: https://dev.azure.com/mseng/Domino/_build?definitionId=7369&_a=summary
-	Here is an example of WAVE’s ATOM.XML file: https://aka.ms/wavevs2019canary 
![image](https://user-images.githubusercontent.com/46505299/90665857-768cb900-e201-11ea-8a96-923dc6bc3d0f.png)

-	This build pipeline modifies our WAVE VSIX to create an ATOM.XML file, which is used to define the private gallery: https://microsoft.visualstudio.com/DefaultCollection/EngSys/_apps/hub/ms.vss-ciworkflow.build-ci-hub?_a=edit-build-definition&id=46056

**Comment by HenokAddis** [comment]
After triage today it seems that @Gabriel is taking the action to drive this to completion with @Larry this week. The current next steps are:
-	See if the existing Build Pipeline can publish to our WAVE Azure static website
-	If not, we may need to clone the build pipeline OR find a new destination for the

**Comment by HenokAddis** [comment]
Updated title to focus on adding Private Gallery for VS

**Comment by lgolding** [comment]
This is done.
