### ISSUE TITLE
LoadSarifLogs API implementation only shows result from last log file

### ISSUE THREAD

**Issue by GabeDeBacker** [microsoft/sarif-visualstudio-extension#163]
The LoadSarifLogs API enumerates through a list of SARIF log paths passed to it.

It currently calls the LoadSarifLog API to do the work of loading each individual SARIF log.

The implementation of LoadSarifLog causes any existing SARIF results to be cleared, so only the last path passed to LoadSarifLogs will display any results.

**Comment by Miaku** [comment]
PR is ready to close out on this. 

ETA to PR completion: EoD Today.

**Comment by GabeDeBacker** [comment]
Verified fixed this morning.
