### ISSUE TITLE
SARIF defects will not be removed from ErrorList even after fixing the issue

### ISSUE THREAD

**Issue by HenokAddis** [microsoft/sarif-visualstudio-extension#166]
Before:
If we have an issue that shows, after it gets 

![image](https://user-images.githubusercontent.com/46505299/90568329-79839d00-e160-11ea-96bb-2895b0aeb84e.png)

**Comment by HenokAddis** [comment]
Even though this did not repro from me, @GabeDeBacker believes there is still an issue from looking at the code.

**Comment by GabeDeBacker** [comment]
This is fixed in version 2.1.11 of the extension
