### ISSUE TITLE
Opening multiple SARIF files will prompt user to select "okay" for every empty SARIF file

### ISSUE THREAD

**Issue by HenokAddis** [microsoft/sarif-visualstudio-extension#167]
Unfortunately as a part of the opening process...for every file that does not have SARIF issues in a multi-file-open, it prompts you to select "Okay"
![image](https://user-images.githubusercontent.com/46505299/90568435-ad5ec280-e160-11ea-80fe-06bc0ca9de54.png)

**Comment by michaelcfanning** [comment]
@lgolding we should be looking at resolving this as part of the nest of work implied by #230.
