### ISSUE TITLE
Unable to open SARIF files through Open -> File 

### ISSUE THREAD

**Issue by HenokAddis** [microsoft/sarif-visualstudio-extension#170]
If you open multiple SARIF files and a normal text file, you will be reproducing the issue:
![image](https://user-images.githubusercontent.com/46505299/90568410-9f10a680-e160-11ea-925f-84c0f4892e63.png)

Only the _objects.mac file opened...where are sarifs? They do not open the actual SARIF files which is the obvious expectation if I open the file itself. We cannot see the content in VS at all. 
![image](https://user-images.githubusercontent.com/46505299/90568513-e434d880-e160-11ea-8aea-2072c20381ab.png)

**Comment by GabeDeBacker** [comment]
This is also inconsistent with the VSCode implementation.
