### ISSUE TITLE
Inline error hyper-link click launches URI with no validation.

### ISSUE THREAD

**Issue by GabeDeBacker** [microsoft/sarif-visualstudio-extension#171]
When a URI is displayed as a hyper-link in the error list, when the URI is clicked there is no validation done on the URI and as a result, it can launch anything which should have some security considerations applied to it.

**Comment by eddynaka** [comment]
@yongyan-gh , can you check this? I think it is already implemented, but let's do a double check!

**Comment by yongyan-gh** [comment]
@eddynaka , the inline hyper link in error list was implemented, but now there is no validation it will directly open the link.
