### ISSUE TITLE
Identify (by default) the engine related to a specific SARIF defect and make that filterable

### ISSUE THREAD

**Issue by HenokAddis** [microsoft/sarif-visualstudio-extension#188]
After we complete this issue ([SARIF Viewer does not show issues even when issues show in problems pane on Import SARIF File](https://github.com/microsoft/sarif-visualstudio-extension/issues/159)) we should consider what defaults are good to show users.

At minimum, based on feedback from Kyle and integrating other DMF engines, we should be distinguishing clearly what engine created what defect and make that easily filterable in the SARIF viewer.

**Comment by Miaku** [comment]
Assigned to: Andrew+Henok

This is a feature that already exists in VS; we should add it to our wiki.

**Comment by mpande98** [comment]
This should be closed. This is already possible.

**Comment by GabeDeBacker** [comment]
The user can already group the error list in visual studio by "tool" to get this behavior.

They may need to turn on the "tool" column first.
