### ISSUE TITLE
We need tooltips to make highlighted segments of the code easier to understand

### ISSUE THREAD

**Issue by HenokAddis** [microsoft/sarif-visualstudio-extension#189]
Any time a line of code is highlighted, the tooltip MUST explain why. There are no tooltips here at all.

--Kyle Sabo

**Comment by Miaku** [comment]
Assigned to: Gabe
ETA: (Investigate)

**Comment by mpande98** [comment]
This issue covers tooltip, crashing issue, and navigating explorer windows issues.
