### ISSUE TITLE
VS opens SARIF file with SARIF extension even though I ask for JSON editor

### ISSUE THREAD

**Issue by lgolding** [microsoft/sarif-visualstudio-extension#196]
Repro:
1. Enlist in the SARIF SDK and open `src\Sarif.Sdk.sln` in VS.
2. In **Solution Explorer**, right-click on the file `src\Test.FunctionalTests.Sarif\TestData\Multitool\ValidateCommand\ExpectedOutputs\SARIF1001.RuleIdentifiersMustBeValid_Valid.sarif` and the select **Open With...**.
3. In the **Open With** dialog, select **JSON Editor** and then click **OK**.

Expected:
The file opens in the editor.

Actual:
The file opens in the editor, _and_ a message box appears: "SARIF Explorer found no results in analysis log...". This demonstrates that the SARIF extension is handling the file even though I asked for the JSON Editor.

This matters because when I open the file as JSON, I'm saying that I don't want to take the time to evaluate the SARIF log and populate the Error List window. I just want to edit the file.

@GabeDeBacker @michaelcfanning FYI

**Comment by michaelcfanning** [comment]
Can you please double-check your results? What should happen now is that the error list should both be populated and the file should open in the editor. This is a change in behavior that @GabeDeBacker introduced after discussion with the team.

You could argue that if someone specifically requested an open operation w/the JSON editor that we shouldn't attempt to process the error list. This could be useful in cases when the log file contains large #'s of results.

**Comment by lgolding** [comment]
Sorry, my description was incorrect. I updated the description to read:

> Actual:
> The file opens in the editor, _and_ a message box appears: ...

My complaint is exactly as you say: If I ask for JSON processing, I don't want the SARIF processing.

**Comment by ArlenTokatlian** [comment]
Triage: Potential workaround to view in VSCode. Valid bug, just need to identify priority.

**Comment by mpande98** [comment]
Low priority

**Comment by mpande98** [comment]
New SDK issue that asks for pretty print to be default

**Comment by lgolding** [comment]
microsoft/sarif-sdk#2098

**Comment by mpande98** [comment]
Checked into SARIF SDK, will be available the next time we publish the SARIF SDK.
