### ISSUE TITLE
Consider adding UI based testing to the extension

### ISSUE THREAD

**Issue by GabeDeBacker** [microsoft/sarif-visualstudio-extension#197]
We need to be verify changes we are making affect the Visual Studio UI (editor display, etc). We need to create test suites to verify the UI changes we are making.

**Comment by ArlenTokatlian** [comment]
Current Opportunity: There is a VS testing model in place today, however could definitely be enhanced by an Apex type implementation. 
Initial consensus is to adopt this existing VS testing model starting as part of the next broad UI changes. 

Additional opportunity (sprit of this ask) is to continue to enhance UI testing capabilities with an Apex type framework for all to use as a forcing function for future UI releases. 

APEX Docs https://devdiv.visualstudio.com/DevDiv/_wiki/wikis/DevDiv.wiki/2287/Apex 

WAVE Docs for APEX https://microsoft.visualstudio.com/DefaultCollection/EngSys/_git/devprod.wave.VsExtension?path=%2FDocumentation%2FE2E%20Tests.md&_a=preview

**Comment by mpande98** [comment]
Has to be done with APEX, there exist deficiencies in VS automation model. Can't tell when certain operations have finished. APEX helps with that problem.

**Comment by lgolding** [comment]
@michaelcfanning Applied new `must-finish` label. This was work in progress that yielded to a higher priority task just at the point where we upgraded .NET Core Framework to 4.7.2. The work in progress (which contains two previously-running tests) no longer built on top of master. It should just be a matter of finding the right versions of the Apex test assemblies.

**Comment by lgolding** [comment]
The Apex-based test framework is in place. We have a single end-to-end test demonstrating the user of the (file-based) viewer interop API to open a log file in the viewer and verify the contents of the Error List. We are now adding new Apex-based tests for new features (such as a test for the stream-based interop API).
