### ISSUE TITLE
SARIF Explorer Tool window does not change to SARIF result (error) when navigating cursor..

### ISSUE THREAD

**Issue by GabeDeBacker** [microsoft/sarif-visualstudio-extension#198]
When a SARIF log is processed the tags are added to any open documents when the users opens them (for example by double clicking on the file in solution explorer or file-open)

When the user is navigating the caret through the document into a highlighted region the SARIF explorer is not automatically navigated to the SARIF error that contains that highlight.

Currently the "data context" for the SARIF explorer window is only done when a user double clicks on the error list.

**Comment by ArlenTokatlian** [comment]
Roslyn / Prefast behavior alignment investigation desired. Deemed minor issue and will be priorities accordingly. 
MichaelFanning to take a cursory look
