### ISSUE TITLE
Double-clicking result does not navigate to source file

### ISSUE THREAD

**Issue by lgolding** [microsoft/sarif-visualstudio-extension#201]
A SARIF log file contains
```
      "originalUriBaseIds": {
        "TARGET": {
          "uri": "file:///c:/MyProject/"
        }
      },
      ...
      "results: [
        {
          "locations": [
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/Client/Example.cs",
                  "uriBaseId": "TARGET"
                },
```

The file c:\MyProject\Client\Example.cs exists on my machine. But double-clicking the result does not open the file.

In the VS Code viewer, double-clicking the result _does_ open the file and highlight the correct line.

[I will provide a minimal repro for this. The file in which I observed this contains sensitive data.]

@michaelcfanning FYI

**Comment by mpande98** [comment]
- Making sure functionality in VS and VS Code is important. This does work in VS Code. 
- Possible cause of issue: Do not have leading slash

**Comment by mpande98** [comment]
@lgolding
