### ISSUE TITLE
Build pipeline should index sources and publish symbols

### ISSUE THREAD

**Issue by lgolding** [microsoft/sarif-visualstudio-extension#204]
Add an "Index sources and publish symbols" task to the SARIF VSIX Build pipeline. This will enable us to debug Watson crashes in Visual Studio.

Symbol publishing allows Visual Studio to automatically locate the pdbs for the failing build during crash analysis. Source indexing allows VS to view the sources during crash analysis.

@michaelcfanning FYI, requested by @GabeDeBacker

**Comment by michaelcfanning** [comment]
A useful first step here is to provide SNUPKG support for all the supporting SDK packages. This mechanism provides for both PDBs and source publishing. The SARIF VSIX binary PDB itself will need to go through the legacy symbol server publishing mechanism. You are probably aware that the task is named 'index sources and publish symbols'.

**Comment by mpande98** [comment]
- Set goal to resolve the next time we release 
- Work in SDK needs to be done first
- SDK symbols need to be packaged

**Comment by mpande98** [comment]
Larry and Gabe working on this today

**Comment by mpande98** [comment]
- Need to add tasks to VSIX to publish internally 
- Should be creating releases for everything in VSIX

**Comment by mpande98** [comment]
@eddynaka

**Comment by eddynaka** [comment]
@mpande98 @lgolding @GabeDeBacker , what project should we enable the symbols?
