### ISSUE TITLE
Crash occurring when closing and re-opening the same source file multiple times

### ISSUE THREAD

**Issue by GabeDeBacker** [microsoft/sarif-visualstudio-extension#205]
When opening and closing the same source file that has SARIF results rendered in it multiple times, a crash occurs in visual studio.

This is related to issue this Windows bug:

https://microsoft.visualstudio.com/DefaultCollection/OS/_workitems/edit/29582350/

**Comment by mpande98** [comment]
@lgolding

**Comment by mpande98** [comment]
In process of validating PR, should be finished today
