### ISSUE TITLE
Fixes don't work unless DeletedRegion specifies CharOffset/CharLength

### ISSUE THREAD

**Issue by lgolding** [microsoft/sarif-visualstudio-extension#209]
Repro files:

[SquiggleTest.sarif.txt](https://github.com/microsoft/sarif-visualstudio-extension/files/5324293/SquiggleTest.sarif.txt)
[SquiggleTest.cs.txt](https://github.com/microsoft/sarif-visualstudio-extension/files/5324292/SquiggleTest.cs.txt)

Repro steps:

1. Save the attached files.
2. Open the SARIF file in VS.
3. Click on the result in the **Error List** to open the **SARIF Explorer**.
4. Select the **Fixes** tab.
5. Click **Preview** or **Apply**.

Expected:

You see the **Preview** or **Apply** UI.

Actual:

Nothing happens.

Diagnosis:

The problem is that `deletedRegion` is specified with line/column properties, but `ReplacementExtensions.ToReplacementModel` expects `CharOffset`/`CharLength`.

```json
                  "replacements": [
                    {
                      "deletedRegion": {
                        "startLine": 7,
                        "startColumn": 23,
                        "endColumn": 25
                      },
                      "insertedContent": {
                        "text": "42"
                      }
                    }
                  ]
```

Fix:

`ReplacementExtensions.ToReplacementModel` needs to fill out the region is `CharOffset` is absent (has value -1).

That would require the file path to be passed all the way down from where the fix models are created in the `SarifErrorListItem` ctor. 

@michaelcfanning @GabeDeBacker FYI

**Comment by lgolding** [comment]
It's true we're going to change the fix UI to use light bulbs, but `ReplacementExtensions.ToReplacementModel` still needs to do the right thing.

**Comment by mpande98** [comment]
Want to get squiggles and lightbulbs working for fixes.

**Comment by lgolding** [comment]
Per discussion in triage: The spec does _not_ require `deletedRegion` to be specified with offset/length properties:

> **3.57.3 deletedRegion property**
> A `replacement` object **SHALL** contain a property named `deletedRegion` whose value is a `region` object (§3.30) specifying the region to delete.
>
> If the length of the region specified by `deletedRegion` is zero, then `deletedRegion` specifies an insertion point, and the SARIF consumer performing the replacement **SHALL NOT** remove any content.

There's nothing about requiring offset/length properties _vs_ line/column properties, and in fact the spec shows several examples of both.

@michaelcfanning @roywill FYI

**Comment by michaelcfanning** [comment]
I'm sure the original thought here was that requiring the consumer to compute offset/length (based on line/column data) to drive the replacement was not ideal. As you know, there's ambiguity around the column unit between IDE/platform environments which needs to be considered (to cover all cases).

Rather than plumbing data through the system, you might consider expanding regions proactively when processing the log file (on observing the presence of fixes). 

But are we taking a fix here at all? The light-bulb machinery will replace all of this in any case, yes?

**Comment by lgolding** [comment]
@michaelcfanning @GabeDeBacker 

Thanks for reminding me of this. It's fixed in my most recent PR (I'd forgotten I'd filed an issue for it). I use the `FileRegionsCache` to "fully populate" the region before attempting to apply the fix. If the region can't be fully populated, I refrain from displaying the light bulb.

The VS light bulb machinery _per se_ doesn't address this; one way or the other, you have to know _where to put_ the light bulb, and it's the client code that's responsible for that.
