### ISSUE TITLE
Telemetry drops events if package not initialized

### ISSUE THREAD

**Issue by lgolding** [microsoft/sarif-visualstudio-extension#216]
Our extension initializes the telemetry provider when VS initializes (calls `InitializeAsync` on) the package. But if you do **File**, **Open** on a SARIF file without previously having done anything that would _cause_ VS to initialize the package (for example, by invoking one of the extensions menu items on the **Tools** menu), then the "open file" telemetry event is not sent because the telemetry provider hasn't been initialized.

Call stack:
```
Microsoft.Sarif.Viewer.dll!Microsoft.Sarif.Viewer.TelemetryProvider.WriteEvent(Microsoft.Sarif.Viewer.TelemetryEvent eventType, System.Collections.Generic.Dictionary<string, string> properties) Line 115 C#
Microsoft.Sarif.Viewer.dll!Microsoft.Sarif.Viewer.TelemetryProvider.WriteEvent(Microsoft.Sarif.Viewer.TelemetryEvent eventType, System.Collections.Generic.KeyValuePair<string, string>[] pairs) Line 105 C#
Microsoft.Sarif.Viewer.dll!Microsoft.Sarif.Viewer.ErrorList.ErrorListService.ProcessSarifLogAsync(Microsoft.CodeAnalysis.Sarif.SarifLog sarifLog, string logFilePath, bool showMessageOnNoResults, bool cleanErrors) Line 376 C#
```

Note that ??? is MEF-exported... TODO FINISH THIS

**Comment by mpande98** [comment]
**Medium priority**: User can interact with services without loading extension itself. Extension not initialized, so telemetry not initialized. 

**High priority**: Where does the data in app insights go? Where does the telemetry go??
