### ISSUE TITLE
Developers should get confirmation that code analysis has run but no defects were found

### ISSUE THREAD

**Issue by michaelcfanning** [microsoft/sarif-visualstudio-extension#230]
VS XP for successful analysis should keep in sync with this issue:

https://github.com/microsoft/sarif-vscode-extension/issues/365

Once PR #272: "Handle additional error bar scenarios" is merged, this will be the status for handling log files received through the stream-based interop API (which is used in the background analysis scenario):

- [x] Scenario <span>#</span>1: No log file is received. This isn't the viewer's responsibility to handle.
- [x] Scenario <span>#</span>2: Malformed file: Implemented with info bar with an red "error" icon.
- [x] Scenario <span>#</span>3: Catastrophic tool failure. In error list + summary in info bar with red "error" icon.
- [x] Scenario <span>#</span>4: Catastrophic configuration failure. In error list + summary in info bar with red "error" icon.
- [x] Scenario <span>#</span>5: No results: Will implement with info bar with a blue "information" icon.
- [x] Scenario <span>#</span>6: Analysis succeeds and there were results. Was already handled.
- [x] Scenario <span>#</span>7: Mixture of previous scenarios. No additional work implied.

We also need to...

- [x] Integrate exceptional condition handling into the file-based interop API (which is used in the WAVE scenario).
- [ ] Related: #167: "Opening multiple SARIF files will prompt the user to select "ok" for every empty SARIF file."
- [ ] Related: #279: Stream-based and file-based APIs must be at parity for downlevel SARIF and native tool output

**Comment by mpande98** [comment]
Banner-driven model is possible. 

In Visual Studio, this is called the info bar. More details here: https://microsoft.visualstudio.com/DefaultCollection/EngSys/_git/devprod.wave.VsExtension?path=%2FWave.VS%2FUtilities%2FInfoBar.cs&_a=contents&version=GBtsunami

**Comment by mpande98** [comment]
Scenarios:

Log file fails to materialize (no log file)
Bad log files (malformed and unexpected file exceptions) **
Log file internally indicates a catastrophic tool failure
Log file indicates a catastrophic configuration failure
Analysis succeeded but there's no results
Analysis succeeded and there are results // Goal scenario
Mixture of 6&everything before it (some results, some failures)

**Comment by mpande98** [comment]
Spec linked: https://microsoft-my.sharepoint.com/:w:/p/malpande/ERFv-DPh2UJJrO_MLRQzd2YBXhson5ZBU1CEl4_wmki7WQ?e=S2XZoK

**Comment by mpande98** [comment]
Update:
Larry is working on Scenario #2 along with Issue #251

**Comment by michaelcfanning** [comment]
To clarify, for scenario #1 there may be little/no SARIF work. The viewer cannot raise errors on the absence of files passed to the viewer without a concrete understanding of how many were expected. 

Now, we could consider some sort of pipeline/API for an synchronous SARIF viewer interaction to raise this condition (i.e., 'one or more SARIF log files could not be generated'). The question is whether we would handle this in a narrow way (e.g., by requiring callers to specify the # of log files that *should* have been produced along with the array of logs that *could* be produced), or simply by adding a more direct error reporting mechanism. Also, a caller could simplify synthesize its own SARIF reporting these catastrophic conditions and send them on as a replacement for the SARIF it failed to produce.

Finally, of course, a caller could simply raise its own InfoBar/other messages to document conditions it has relevant (sole) knowledge to report.
