### ISSUE TITLE
Migrate from AppVeyor to GitHub-driven ADO pipelines

### ISSUE THREAD

**Issue by lgolding** [microsoft/sarif-visualstudio-extension#232]

**Comment by mpande98** [comment]
Migrated SDK to build with GIthub actions

**Comment by eddynaka** [comment]
Hi @mpande98 , for the release pipeline, do we have a reason to be in Azure Devops Pipeline?

**Comment by eddynaka** [comment]
And one important thing, we need someone with admin permission to start a "dumb" action to trigger it.

**Comment by eddynaka** [comment]
Quick update: we are getting the permissions to create the pipeline. Will keep you updated!
Thank you!

**Comment by eddynaka** [comment]
Just created the PR.

I couldn't use the `BuildAndTest.ps1` because the `windows-latest` couldn't find the `msbuild` command.

So, I changed to the following steps:
- nuget restore task
- msbuild task
- vstest task
