### ISSUE TITLE
Apply uniform style guidelines to repository

### ISSUE THREAD

**Issue by lgolding** [microsoft/sarif-visualstudio-extension#237]
... while it's still small. Let's add it to the interop project while we're at it.

**Comment by mpande98** [comment]
Sarifer = another VSIX which gives menu items

**Comment by lgolding** [comment]
Let's bite the bullet and do it for all the projects.

**Comment by michaelcfanning** [comment]
@eddynaka, can you work your .editorconfig magic on this repo?

**Comment by eddynaka** [comment]
@lgolding @michaelcfanning , I just created a PR with this.

Should we use the same rules that we have in sarif-sdk? For example, should we separate in groups (that's the only rule that I didn't enable here yet).

**Comment by lgolding** [comment]
IMO yes, we should use the same rules as the SARIF SDK.
