### ISSUE TITLE
Error list shows all sentences in multisentence output

### ISSUE THREAD

**Issue by michaelcfanning** [Microsoft/sarif-visualstudio-extension#28]
We correctly create an expander for multisentence error list entries. But we show the full contents for the unexpanded error list entry. we should only show the first sentence for this case (and the remainder of the error should display when expanded).

**Comment by EasyRhinoMSFT** [comment]
@michaelcfanning what are you seeing?

**Comment by michaelcfanning** [comment]
Sorry, had to chase down a repro. Here it is:

1) create a SARIF file with a result that has a single sentence with no trailing period

result: we create an expand for this case that shows the content, unnecessarily. we also appear to append a period to the single sentence as it appears in the error list.

**Comment by EasyRhinoMSFT** [comment]
We determine whether to show the expando by comparing Message and ShortMessage. We get ShortMessage by calling Sarif.ExtensionMethods.GetFirstSentence, which appends a period in all cases. If Message doesn't have a period as its last character, the strings don't match. So the fix is to trim the period from the return of ExtensionMethods.GetFirstSentence.

**Comment by michaelcfanning** [comment]
Are you sure we need to modify GetFirstSentence? Seems like you could simply update the comparison behavior. For example, if ShortMessage.StartsWith(Message) that would work (but could be non-obvious). You could also compare for an exact match and, on failure, check for the case where ShortMessage is greater in length by one char and ends in a '.'.

@lgolding, any thoughts? i see the case for asking why GetFirstSentence is engaging in this behavior. It is, however, enforcing a specified behavior (though the spec allows for possibility some other punctuation might be appropriate). I suppose an exclamation point or a question mark might work in English:

'Why did you introduce an XSS vulnerability at MyClass::InsecureMethod()?'

"A plain text message SHOULD be expressed as a single paragraph of plain text, consisting of one or more complete sentences, each ending with a period (or appropriate punctuation for the language in which the message is written). A plain text message SHOULD be expressed as a single paragraph of plain text, consisting of one or more complete sentences, each ending with a period (or appropriate punctuation for the language in which the message is written). "

**Comment by EasyRhinoMSFT** [comment]
Yes that's what I meant. No SDK change.

**Comment by lgolding** [comment]
Even in English this is a hard problem (see https://english.stackexchange.com/questions/406194/which-symbols-can-end-a-sentence), and perhaps we shouldn't devote time to it.

**Comment by michaelcfanning** [comment]
I get a bit worried about paralysis in the common case because we aspire to handle all sentence terminations in all languages. If we don't understand in the common case when a sentence ends, there's no reason at all for GetFirstSentence, much less worry about whether it appends a period.

Note that this issue wasn't driven by a complaint over the current behavior of GetFirstSentence. What I'd like to resolve is the problem of us injecting an expander in the error list in cases where the result isn't terminated with a period. I suggest we fix that and we can keep an eye on GetFirstSentence behavior moving forward.

**Comment by lgolding** [comment]
I agree. I drop my suggestion that we should improve `GetFirstSentence`. Most of the corner cases:

- "Dr. Smith is a stowaway." (period after an abbreviation)
- "He said 'This is a test.'" (period isn't actually the last character)

... aren't likely to occur in error messages. Yes, let's just keep an eye out for problems here.

**Comment by michaelcfanning** [comment]
The convention I've used in the past is for these helpers to ignore any content that is itself wrapped in quotes. This allows injection of content into a string such as what's below.

'Dr. Smith' is not a recognized person.

Basically, tools providers should consider enquoting any content that they can't strictly control.

'{0}' is not a recognized person.

The format string above will reliably handle any injected content except for single quotes. Yes, I know that you prefer double-quotes for this scenarios. :)

**Comment by EasyRhinoMSFT** [comment]
GetFirstSentence actually DOES append a period:
return text.TrimEnd('.') + ".";

I fixed the expando bug by removing it if the original string doesn't end with a period.

**Comment by EasyRhinoMSFT** [comment]
And there is a good unit test that shows what this method can handle:
.\src\Sarif.Driver.UnitTests\Sdk\ExtensionMethodsTests.cs

**Comment by michaelcfanning** [comment]
Yes. And we're leaving this behavior alone for now. Thanks for fixing the expander issue.
