### ISSUE TITLE
Background analysis: Pattern matching

### ISSUE THREAD

**Issue by lgolding** [microsoft/sarif-visualstudio-extension#282]
Items marked with __*__ explicitly mentioned by @michaelcfanning; other requirements inferred:

- [x] Implement right-click "Analyze solution" menu item:
    - [x] Clear all background-analysis-generated items.
    - [x] Stop any running per-solution analysis.
    - [x] Stop all running per-project analyses.
    - [x] __*__ Read `.spam` folder.
    - [x] __*__ Start new per-solution analysis.
- [x] On completion of per-solution analysis:
    - [x] Remove existing per-solution error list entries.
    - [x] Remove existing per-project error list entries for all projects.
    - [x] Insert new per-solution error list entries.
- [x] Implement right-click "Analyze project" menu item:
    - [x] Clear all background-analysis-generated items.
    - [x] Stop per-project analysis for this project.
    - [x] __*__ Read `.spam` folder.
    - [x] __*__ Start new per-project analysis.
- [x] On completion of per-project analysis:
    - [x] Remove existing per-project error list entries for this project.
    - [x] Insert new per-project error list entries.
- [x] When user closes solution:
    - [x] Stop per-project analyses.
    - [x] Remove per-project error list items.
    - [x] Stop per-solution analysis.
    - [x] Remove per-solution error list items.
- [x] __*__ Do not duplicate Error List items between per-project, per-solution, and individually opened files.
- [x] Do not analyze an individually opened file while a solution-wide analysis is in flight.

**Comment by eddynaka** [comment]
Hi @michaelcfanning / @lgolding , this issue is complete.
Can you download the main branch and test it?

Thank you :)
