### ISSUE TITLE
Closing a source file doesn't remove background analysis error list items

### ISSUE THREAD

**Issue by lgolding** [microsoft/sarif-visualstudio-extension#283]
That's because `BackgroundAnalyzerBase.StartAnalysisAsync` does not provide a `logId` as a second argument to `IBackgroundAnalysisSync.ReceiveAsync`. As a result, the `ErrorListService` does not make an entry for this file in `RunIndexToDataCached`.

**Comment by lgolding** [comment]
The fix for this is merged into `feature/spam`.

**Comment by michaelcfanning** [comment]
We need a UI test for this scenario.

**Comment by lgolding** [comment]
Reopening. This doesn't actually work. It worked at one time and then broke (which, as @michaelcfanning mentioned, highlights the need for a UI test for it).

**Comment by michaelcfanning** [comment]
I've labeled this with 'author-ui-test'. Let's complete that task before closing this issue.

**Comment by eddynaka** [comment]
@michaelcfanning , my bad, i probably linked the wrong issue.

**Comment by lgolding** [comment]
`author-ui-test`, nice. Pretty color, too.

**Comment by yongyan-gh** [comment]
@michaelcfanning / @eddynaka 
this works in my machine with latest version of vs extension. I cannot repo the issue. Please let me know if any repo step can repo the issue. Will create ui tests for this scenario.

**Comment by eddynaka** [comment]
I think I already fixed. We just have to:
1. double-check
2. check if we already have a test that validates it

If both are true, close the issue :)

**Comment by eddynaka** [comment]
with our merged pr, we can safely close this! thank you!
