### ISSUE TITLE
No line numbers in error list if results have only offset/length

### ISSUE THREAD

**Issue by lgolding** [microsoft/sarif-visualstudio-extension#288]
If you open a SARIF log file whose result location regions contain only offset/length properties (that is, they do _not_ contain line/column properties), then the Error List's Line and Col columns show 0.

This is because, for performance reasons, we only call `FileRegionsCache.PopulateTextRegionsProperties` when _navigating_ to an error from the Error List.

Another aspect of this bug is that, even after navigating, when we now have the line/column information in hand, we don't update the Error List item: it still shows Line, Col as 0.

@GabeDeBacker @michaelcfanning @eddynaka

**Comment by lgolding** [comment]
Can we "fault in" the line numbers as Error List items become visible? Does the Error List display virtualization permit this?

**Comment by yongyan-gh** [comment]
When we open a sarif log file in Sarif viewer, it creates error list items with line/column number based on results of Sarif log, without parsing actual file of the results. 
If the result location regions defined by offset/length, its start/end line/column properties should be 0. This is why line/column show 0 for offset/length results.

When we navigate to the error list item (e.g. double click it) with only offset/length region, viewer will try to resolve the file path and read file content, then calculate the start/end line/column using offset/length.

Question is should viewer try to resolve file path & read file content for each result when Sarif log is loaded? 
Or we can populate the line/column after navigate to that item.

**Comment by EasyRhinoMSFT** [comment]
We definitely can't open files when the log is loaded. @yongyan-gh let's try your second suggestion, I think it could be a fairly simple fix.

**Comment by yongyan-gh** [comment]
Tried the solution updating the Sarif error list item after resolving the actual line/column number.
But seems we didn't implement a mechanism to update a single ErrorList table entry. We can use `ITableDataSink` to remove old entry and add newly updated entry, or replace the entry. Looking into this solution.
