### ISSUE TITLE
Implement comprehensive/basic feedback collection

### ISSUE THREAD

**Issue by michaelcfanning** [microsoft/sarif-visualstudio-extension#293]
We need to collect feedback on results, as we do in VS Code.

This is the "bucket" item.

**Comment by lgolding** [comment]
We are starting off with the right-click gesture on the Error List (see #292), but we want to get it into the lightbulb UI as well.

**Comment by eddynaka** [comment]
@michaelcfanning , is this something like:
in the error list we have 10 errors showing, then we select a few -> right click -> feedback.

Is that correct?

**Comment by michaelcfanning** [comment]
This is definitely a valid scenario. It raises the question of how we'll handle a situation where users select a mixture of our error list items and others (like intellisense warnings). It may be ok to start with a capability to select and provide feedback on a single error list item only (and revisit the multi-item scenario next).
