### ISSUE TITLE
Add core UI 'smoke' end-to-end functional tests

### ISSUE THREAD

**Issue by lgolding** [microsoft/sarif-visualstudio-extension#300]
- [x] Error list populated on solution analysis
- [x] Error list populated on project analysis
- [x] Error list populated on file open.
- [x] Background analysis on user edit.
- [x] Error list empty after file close.

**Comment by mpande98** [comment]
This issue is about implementing our core UI tests

**Comment by yongyan-gh** [comment]
Error list empty after file close. this is verified in UI tests

**Comment by eddynaka** [comment]
@yongyan-gh, create the missing test since we merged the pr

**Comment by yongyan-gh** [comment]
background analysis on user edit was implemented by #349
UI automation tests was added @ https://github.com/microsoft/sarif-internal/pull/12
