### ISSUE TITLE
Code highlight disappears on SARIF explorer "Info" tab click

### ISSUE THREAD

**Issue by cfaucon** [microsoft/sarif-visualstudio-extension#31]
Repro Steps:
1. Open SARIF in viewer
2. Select issue in error list that opens source code with proper highlighting
(snippet is highlighted properly)
3. In SARIF explorer window, click "Info" tab

Expected: Source highlighting should still exist
Actual: Source highlighting is remove and no longer present in source code

**Comment by eddynaka** [comment]
@yongyan-gh , lets check this

**Comment by yongyan-gh** [comment]
Cannot repro this issue with latest VS extension, 
1. Click on result and file opened with highlighted text, focus is in the editor. Sarif Explorer shows up.
![image](https://user-images.githubusercontent.com/76094515/107134827-6d280380-68aa-11eb-9495-87882a42551f.png)

2. Click on Info tab of Explorer. Editor loses focus and Sarif Explorer get focus. But text in editor is still highlighted
![image](https://user-images.githubusercontent.com/76094515/107134866-b415f900-68aa-11eb-81c2-e6ccb0b78b54.png)

Please let me know if anyway can repro the issue.

**Comment by eddynaka** [comment]
@yongyan-gh , just to double check, try to use the version from the store.

**Comment by yongyan-gh** [comment]
yes i can repro this issue in market place version.

**Comment by eddynaka** [comment]
Ok, closing since this will be replaced for the new extension soon
