### ISSUE TITLE
Error list expanders are broken.

### ISSUE THREAD

**Issue by michaelcfanning** [microsoft/sarif-visualstudio-extension#330]
1. Create a SARIF file with a result with text == "This is a sentence. This is another."
2. Open it in VS.

Expected: VS error list item shows the first sentence and has an expander which can be used to view both.

Actual: Only the first sentence is displayed with no expander.

**Comment by eddynaka** [comment]
@michaelcfanning, I was looking at this today and I saw that even the extension that we have in the marketplace isn't working. Debugged a little and I saw that our functions are getting called, but the interface isn't changing.
