### ISSUE TITLE
Create configuration file for background analysis (e.g, .spam\config.json or .spam config.yml)

### ISSUE THREAD

**Issue by michaelcfanning** [microsoft/sarif-visualstudio-extension#335]
If we prefer a JSON file, we'd need to exclude it from rules loading. Maybe explore using YML? 

We can start with a single setting:

BackgroundAnalysisEnabled=true;

... when set to false, background analysis should cease. The right-click menu analyze project and analyze solution commands will still be available.

**Comment by eddynaka** [comment]
Hi @michaelcfanning , in this case, that property will only block the file analysis type. Is that correct?

If that is the case, should we rename to FileBackgroundAnalysisEnabled, with that, we could have a global one (which would disable all kinds).

**Comment by eddynaka** [comment]
Going to JSON it would be easier to parse.

If we go with YML, the parse might be a little harder, unless we use a pre-existing package.

**Comment by yongyan-gh** [comment]
So we need to find the .spam folder and config.json file in solution root folder?
User may open a individual file not a part of solution.
If cannot find config file, default value will be applied.

**Comment by yongyan-gh** [comment]
Another option is to create a visual studio option/option page for sarif extension.

**Comment by yongyan-gh** [comment]
for example:
![image](https://user-images.githubusercontent.com/76094515/105435277-eddfd200-5c11-11eb-862a-45c73772eb2e.png)

**Comment by yongyan-gh** [comment]
For example:
![image](https://user-images.githubusercontent.com/76094515/105435365-18318f80-5c12-11eb-8f5c-98a5039f42a4.png)

@michaelcfanning @eddynaka  what do you think?

**Comment by eddynaka** [comment]
@yongyan-gh , how does that work? for example, does it save the data somewhere? if yes, where? will the saved that be shared between solutions?

**Comment by yongyan-gh** [comment]
@eddynaka 
according to this [link](https://docs.microsoft.com/en-us/visualstudio/extensibility/internals/creating-options-pages?view=vs-2019#persist-tools-options-page-state), the option is saved per visual studio profile by default. No coding needed.

> Persist Tools Options page state
> If a Tools Options page implementation is registered with automation support enabled, the IDE persists the page's state along with all other Tools Options pages.
> 
> A VSPackage can manage its own persistence by using ProvideProfileAttribute. Only one or the other method of persistence should be used.

**Comment by eddynaka** [comment]
I think it's a nice and clean idea! And everything would be in one place, just like all the other features.

Let's do it! :)

**Comment by eddynaka** [comment]
Update: we created the window with two options: enable automatic analysis and enable automatic analysis for sarif files.
we can add more options later if needed
