### ISSUE TITLE
Don't analyze .SARIF files by default.

### ISSUE THREAD

**Issue by michaelcfanning** [microsoft/sarif-visualstudio-extension#337]
The reason is that SARIF files themselves are reporting data captured in other files. Currently, the background analyzer interferes with the SPAM development process because it analyzes log files as well as targets that contain, for example, insecure patterns.

We could add a deny list regex to the SARIF configuration settings file, when available, that has this default:

FileNameDenyRegex=^.*.\sarif$

And file name matching this regex would be excluded from analysis.

**Comment by eddynaka** [comment]
should this be part of the SPAM or should we add this logic in the sarifer?

**Comment by eddynaka** [comment]
we add this in the sarifer option. So, all configurations will be there.
