### ISSUE TITLE
VS crashes when you try to fix an issue

### ISSUE THREAD

**Issue by eddynaka** [microsoft/sarif-visualstudio-extension#356]
1. Create a sarif  file with a result and a fix.
2. double click the result
3. right side, window, click preview or apply
4. vs will crash

[sample_sarif.txt](https://github.com/microsoft/sarif-visualstudio-extension/files/5882976/sample_sarif.txt)

**Comment by eddynaka** [comment]
[temp.txt](https://github.com/microsoft/sarif-visualstudio-extension/files/5883630/temp.txt)

[sample_sarif.txt](https://github.com/microsoft/sarif-visualstudio-extension/files/5883633/sample_sarif.txt)

rename sample_sarif.txt to sample_sarif.sarif and try again

**Comment by yongyan-gh** [comment]
This is because the sarif log result.fixes.replacements.deletedRegion doesn't have charOffset, the default value is -1. There is a check in fix.CanBeAppliedToFile only returns fix which replacement.Offset >=0

**Comment by eddynaka** [comment]
Since this is related to an old version, let's try to publish the new version.
