### ISSUE TITLE
Installation instructions for SARIF viewer extension references "Visual Studio 2109"

### ISSUE THREAD

**Issue by juliego** [microsoft/sarif-visualstudio-extension#404]
Installation
In Visual Studio 2109, select menu item Extensions > Manage Extensions.
In the tree view, select the Online node.
In the Search text box, type "sarif" and then press ENTER.
In the Microsoft SARIF Viewer tile, select Download.

**Comment by eddynaka** [comment]
Hi

we have the same information here: https://github.com/microsoft/sarif-visualstudio-extension/blob/main/Content.md
We will link both in the future.

thanks!
