### ISSUE TITLE
Asking to open a file which is already open

### ISSUE THREAD

**Issue by eddynaka** [microsoft/sarif-visualstudio-extension#413]
Hi,

create a result where the location points to this:
https://raw.githubusercontent.com/microsoft/sarif-visualstudio-extension/main/BuildAndTest.cmd

double click and wait for the magic.

it will
1. download the file
2. open a windows asking for u to open a file

**Comment by yongyan-gh** [comment]
This issue was resolved by this change: 
https://github.com/microsoft/sarif-visualstudio-extension/pull/416
