### ISSUE TITLE
Incompatible with VS 2022

### ISSUE THREAD

**Issue by ssg** [microsoft/sarif-visualstudio-extension#439]
I don't think there's any blocker to release this extension for VS 2022.

**Comment by ssg** [comment]
@eddynaka I incorrectly bumped into this (bing search returns this as the result when searched). That's why I thought it was incompatible. Apparently there's a separate "2022" edition of the extension here: https://marketplace.visualstudio.com/items?itemName=WDGIS.MicrosoftSarifViewer2022

Feel free to close this. Thanks.

**Comment by eddynaka** [comment]
Hi @ssg,

yeah, we once tried to ship one extension that supports both versions 2019 and 2022.
But, that generated an issue and the VS team asked us to separate both.

:)

Based on that, closing the issue!
thank you!

**Comment by giggio** [comment]
It would be a good idea to link to the 2022 edition of the extension on the readme, and also from the 2019 page in the marketplace, inform that there is a 2022 version.

**Comment by eddynaka** [comment]
@yongyan-gh can you change the README, pls?

@giggio , thanks for the suggestion!
