### ISSUE TITLE
VS2019 fresh download of VSIX did not work for me

### ISSUE THREAD

**Issue by michaelcfanning** [microsoft/sarif-visualstudio-extension#453]
@EasyRhinoMSFT, how about for you?

**Comment by yongyan-gh** [comment]
@michaelcfanning what error/issue did you see? 
I refresh installed the marketplace SARIF viewer on VS 2019, it works for me.

**Comment by yongyan-gh** [comment]
Also clean installed the VS2019 VSIX built from latest main branch. It also works. Pls let me know what issue did you see thanks!

**Comment by EasyRhinoMSFT** [comment]
I don't see the tool window, and if I go to View > Other windows, it comes up empty. This is the live package.

**Comment by yongyan-gh** [comment]
@EasyRhinoMSFT I cannot repo your issue neither...  Ran the APEX tests all passed too. Wondering if its environment related. Feel free to setup a meeting/live session we can investigate more.

![image](https://user-images.githubusercontent.com/76094515/151058349-307e3a42-79d0-47de-81de-37f7041ec86a.png)

**Comment by yongyan-gh** [comment]
Worked with @EasyRhinoMSFT showed me the issue:
1. Open VS 2019 installed the SAIRF viewer extension.
2. Open a valid SARIF log file with results.
3. SARIF explorer does not popup automatically
4. Open SARIF explorer from menu 'View' -> 'Other Windows' -> 'SARIF Explorer', the explorer window is blank.

As I understand this is current viewer's behavior. Viewer does not open SARIF explorer after opening a SARIF log file. 
Only when   you navigate to the result in Error List pane (double click on the error list item), it will open SARIF explorer and populate information. 

I found an old issue discussing about this behavior at #159. Please take a look.
We could show a message in the blank SARIF explorer "Select an error to see details" to the user.

**Comment by EasyRhinoMSFT** [comment]
I find this very weird. The original purpose of the viewer was to provide an enhanced interaction with SARIF logs with a UI that presents their details. The current behavior makes it almost completely invisible and difficult to discover.

**Comment by tgriff** [comment]
I too am confused by the behavior here. This morning I downloaded and installed it on VS2019. I opened a valid SARIF file (works fine with the VSCode extension) but I don't see anything in the Error List or in the SARIF Explorer window. I even opened the Solution to which the SARIF file applies but I still don't see anything. My expectation is that I should see results for any SARIF file I open _somewhere_. Any logs or anything I can collect here?

**Comment by michaelcfanning** [comment]
My machine is still in this condition. I see that the extension is installed, 3.0.59.39815. I know that the viewer is partly operational: if I open a SARIF v1 file it queries me to see if I want to transform. And then, after this, silence. :) 

@yongyan-gh, @EasyRhinoMSFT, with two customer reports, I trust there's some fire to this smoke. :) Would you like me to debug my system, if no one else on the team can repro?

**Comment by EasyRhinoMSFT** [comment]
@michaelcfanning can you please provide the log you are opening

**Comment by yongyan-gh** [comment]
@tgriff @michaelcfanning 

can you pls share the visual studio log file at: %APPDATA%\Microsoft\VisualStudio\\{vs_version}\ActivityLog.xml, and the sarif log file you opened when you saw the issue? Thanks
