### ISSUE TITLE
2022 Version only Shows JSON File

### ISSUE THREAD

**Issue by garfbradaz** [microsoft/sarif-visualstudio-extension#466]
Hey Everyone

Downloaded a fresh 2022 version today, so I can view .NET Upgrade Assistants output mentioned here:

https://dotnet.microsoft.com/en-us/platform/upgrade-assistant/tutorial/install-upgrade-assistant

Now when I open the file using `Tools->Open Static Files as SARIF`, it just opens as a JSON file:

![image](https://user-images.githubusercontent.com/959766/159274864-d8b1ad10-a106-4899-a07a-a831cbc59924.png)

Also the _SARIF Explorer_ doesn't show anything:

![image](https://user-images.githubusercontent.com/959766/159275712-b7e778aa-137f-4ccf-843c-4f5e48ce22f8.png)

**Comment by CharlieGMH** [comment]
I'm experiencing the same result, with VS 2022 and with 2019.

**Comment by VatroslavSrzic** [comment]
Same here. VS 2022.

**Comment by jwalker-hw** [comment]
same vs 2019

**Comment by ddonabedian** [comment]
Same here. VS 2022

**Comment by puneetpawaia** [comment]
Same here. VS 2022 (17.2.6)

**Comment by jstevenson72** [comment]
Same in VS 2022 Professional 17.3.0

**Comment by yongyan-gh** [comment]
Thanks for reporting the issue.

After you open a valid SARIF file using SARIF Viewer extension for VS using menu `Tools -> Open Static Analysis Results as SARIF`, all the results of the SARIF file are loaded into VS built-in error list window. If you don't see the error list window, you can open it using menu `View -> Error List`.

Below is the screenshot of the error list window loaded with results from a SARIF file.
![image](https://user-images.githubusercontent.com/76094515/189443657-1312e55b-6e1a-44d8-9bcc-fc5f5bf1ca97.png)

The SARIF Explorer window only show detailed information of the result in the error list window, like the rule's full description, related locations etc., after you navigate to it (by double clicking on the result).

Below is the screenshot of the SARIF explorer window shows detailed information of a selected result.
![image](https://user-images.githubusercontent.com/76094515/189445719-7105fadc-e21f-4a27-a87b-449562cb7e45.png)

If the SARIF file is not a valid SARIF file according to the SARIF json schema, the extension should show an error in the VS infobar with error message like the screenshot below, the no result will be loaded into the error list window.
![image](https://user-images.githubusercontent.com/76094515/189446262-9e216ff5-ee67-4307-8bba-9389c1d8585e.png)

There is a web validator tool to validate if the SARIF file is valid at https://sarif.info/Validation

If the SARIF file is valid, but you cannot load the results using the extension, can you please share you file and we can take a look what is the issue.


Thanks a lot!

**Comment by EasyRhinoMSFT** [comment]
Seems like this is behaving as designed; however, the confusion is apparent so we'll investigate options for addressing that.
Opened issue https://github.com/microsoft/sarif-visualstudio-extension/issues/551
