### ISSUE TITLE
Fix background color for extension settings

### ISSUE THREAD

**Issue by marmegh** [microsoft/sarif-visualstudio-extension#495]
![image](https://user-images.githubusercontent.com/30842915/177824247-23ce751b-5b02-42cf-80eb-6f5f9d5a0f3c.png)
The background color for the SARIF and SARIFER VS extensions is nonstandard.

**Comment by EasyRhinoMSFT** [comment]
Fixed in merge 499
https://github.com/microsoft/sarif-visualstudio-extension/pull/499
