### ISSUE TITLE
SARIF viewer code finder issue

### ISSUE THREAD

**Issue by yongyan-gh** [microsoft/sarif-visualstudio-extension#609]
related [Bug 2116514](https://dev.azure.com/mseng/1ES/_workitems/edit/2116514): SARIF viewer pops up code finder, even when file is available

I think there are 2 issues mentioned in the bug:

1. SARIF viewer pops up file open dialog immediately after opening a SARIF log, tries to re-map the results file location to your local file path. Its pops up the dialog for each result even the result file location point your local file path already.

2.  This re-mapping process usually happens when user navigate to the result in ErrorList (double clicking). 

Attached the repro SARIF log file. [repros.zip](https://github.com/microsoft/sarif-visualstudio-extension/files/13075455/repros.zip)

**Comment by yongyan-gh** [comment]
@EasyRhinoMSFT / @edkazcarlson-ms , a question about code finder:

In `ErrorListService.WriteRunToErrorList()` method, it calls code finder to try to find best match for each SARIF result after loading a SARIF log. 

Is it a hard requirement to make the code finder work? Or can it be happened when user navigates to the particular results (double clicking the error item)? the viewer used to do the file location remapping when user navigates to the result, not after loading a SARIF result.

https://github.com/microsoft/sarif-visualstudio-extension/blob/83f587986b4cd0e17f64d4410f5123b406a7cc1c/src/Sarif.Viewer.VisualStudio.Core/ErrorList/ErrorListService.cs#L705

**Comment by yongyan-gh** [comment]
@edkazcarlson-ms thanks for looking! lets look at the first issue for now. Below is my repro envionrment and steps:

Commit: 83f587986b4cd0e17f64d4410f5123b406a7cc1c
VS version: 17.7.6

Repro:

1. Download the attached zip file and unzip the file to your local disk, e.g. "C:\SarifLog". Then the sarif log file path should be "C:\SarifLog\repros\testthis\repro.sarif".
 
2. Edit above repro.sarif file, make sure the only result's `artifactLocation.Uri` path points to the file in your local path. e.g. "file:///C:/SarifLog/repros/testthis/Azure/azure-data-labs-modules/5690656642/1_Run%20Terratest.txt". 

3. Launch VS and open the repro.sarif log file.

Expected behavior: 

- The viewer opens the Sarif log content in editor window and load the 2 results in the ErrorList window, without popping up a 
  open file dialog asking user to select the target file, because the Sarif log result already point to the file in your local disk.

Actual behavior:
- The viewer pops up open file dialog asking the target file location, after user selects the target file, it opens the Sarif log content in editor window and load the 2 results in the ErrorList window.

Let me know if any question to repro. Thanks!

**Comment by edkazcarlson-ms** [comment]
I see the issue now, I was initially opening to the folder and then opened the .sarif file. If I have a "blank" vs editor state and open the .sarif file only I repro the bug you mentioned.
Thank you, I'll look into the issue at hand.

**Comment by edkazcarlson-ms** [comment]
@yongyan-gh I believe I have fixed the bug, please confirm that the changes in https://github.com/microsoft/sarif-visualstudio-extension/pull/611 fix the issue you are seeing :)

**Comment by edkazcarlson-ms** [comment]
Also usually Chris reviews my PR's but it seems like he's OOF, could you review https://github.com/microsoft/sarif-visualstudio-extension/pull/610 along with https://github.com/microsoft/sarif-visualstudio-extension/pull/611 when you get the chance? Thank you.
