### ISSUE TITLE
Cannot open SARIF files containing URIs that are empty strings

### ISSUE THREAD

**Issue by simmse** [microsoft/sarif-visualstudio-extension#85]
If I attempt to open the /analyze:log sarif output from Visual Studio 2019 (16.0.3 release or 16.1.0, preview 2), both Visual Studio 2019 and Visual Studio 2017 produce the same error dialog.  It says, "Value cannot be null.  Parameter name: path."  I have no information within the standard that says a path parameter exists.  Please refer to [section I.5 of the official standard ](http://docs.oasis-open.org/sarif/sarif/v2.0/sarif-v2.0.html).  

I suppose there is a small chance that the _environmentVariables_ area under invocations is the cause.  However, when I search the sarif file output from Visual Studio 2019, there is no entry anywhere in the file that is tagged _environmentVariables_.  If this is an issue with Visual Studio 2019, then it would make sense.  This file output type is not listed on [the official analyze option page for 2019](https://docs.microsoft.com/en-us/cpp/build/reference/analyze-code-analysis?view=vs-2019).  For this issue, use the Microsoft [Sample C++ project for code analysis](https://docs.microsoft.com/en-us/visualstudio/code-quality/demo-sample?view=vs-2019).

**Comment by simmse** [comment]
I have just tested with a [web beta sarif validator](https://sarifweb.azurewebsites.net/Validation).  The outcome is exactly the same as this extension.  I do not know from this result, whether the root cause is within the extension, Visual Studio, or [the JSON based schema](http://docs.oasis-open.org/sarif/sarif/v2.0/csprd01/schemas/sarif-schema.json).

**Comment by lgolding** [comment]
@simmse Can you share a SARIF file that gives you this error? It would be ideal if you had a sanitized (not containing any sensitive or confidential information) and minimal SARIF file that demonstrates the problem.

It would also help if I knew the exact compiler command line that produced the file.

Thanks!

P.S. The error message is from a runtime exception in the code. It's not referring to the name of a SARIF property; it's just a parameter name, from code like this:
```
public void DoSomethingToFile(string path)
{
    if (path == null) throw new ArgumentNullException(nameof(path));
    ...
}
```
It has nothing to do with the SARIF standard.

**Comment by simmse** [comment]
Perhaps something has been modified in the more recent 2019 Visual Studio (e.g. 16.1.4).  When I open with File | Open, the editor area displays the file.  I am not sure what is supposed to happen now.  I can see the sarif (attached).  Beyond that it is not clear what else is supposed to occur.  The preview 2019 version I have is 16.1.0 Preview 2.0.  Please remove the .txt ending to observe .sarif behavior.  Remember that this originates from `[the Demo Sample by Microsoft](https://docs.microsoft.com/en-us/visualstudio/code-quality/demo-sample?view=vs-2019)`
[annotations.nativecodeanalysis.sarif.txt](https://github.com/microsoft/sarif-visualstudio-extension/files/3483930/annotations.nativecodeanalysis.sarif.txt)

**Comment by lgolding** [comment]
Ok, thank you for the repro file. I can reproduce your observation:

1. I am running VS 2019 v16.1.4.

2. I have installed the Microsoft SARIF Viewer extension, v2.1.3 (the latest).

![image](https://user-images.githubusercontent.com/11762653/62743151-2e379a00-b9f6-11e9-9703-ccb0aa99251d.png)

3. I removed the ".txt" extension from the file annotations.nativecodeanalysis.sarif.txt.

4. In VS, I do **File**, **Open** and select annotations.nativecodeanalysis.sarif.

5. The viewer notices that the sample file does not conform to the final, official version of SARIF (which is 2.1.0), and so it automatically translates the file to the latest version, and offers to save the transformed file. I said "No", but you can say "Yes" if you like:

![image](https://user-images.githubusercontent.com/11762653/62743238-7951ad00-b9f6-11e9-8816-9d068a3d1841.png)

6. ... and it crashes:

![image](https://user-images.githubusercontent.com/11762653/62743306-cafa3780-b9f6-11e9-8c82-193af12e95b9.png)

I will debug this and provide a fix. Thanks!

**Comment by lgolding** [comment]
@simmse Ok, I know what the trouble is. In the course of converting from the old to the new version, we aren't handling the empty `helpUri` values in the input file. (Strictly speaking, that makes the input file invalid, but no matter.)

@michaelcfanning FYI. Diagnosing this I found a couple of unrelated bugs in the `PrereleaseCompatibilityTransformer` (@simmse, that's the component in the SARIF SDK that translates old version to the most current.) I will fix all of this, publish a new SDK NuGet, then update the viewer to use the latest NuGet.

I'll take care of this tomorrow.

**Comment by lgolding** [comment]
Well, the root cause wasn't what I thought it was. Still looking. The good news is, I got some nice unit tests out of it ;-)

**Comment by lgolding** [comment]
No, that _is_ the root cause! My test had a bug. Now the test correctly shows the problem. I'll stop the stream of consciousness now...

**Comment by lgolding** [comment]
@simmse, This is fixed. I'll publish a new VSIX to the marketplace as soon as our build pipeline finishes producing a signed binary.

**Comment by lgolding** [comment]
@simmse, version 2.1.4 of the SARIF Viewer extension for Visual Studio is now available on [the marketplace](https://marketplace.visualstudio.com/items?itemName=WDGIS.MicrosoftSarifViewer). Please let me know if this solves your problem.
